### 1. Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is `False`, the `i-th` output column is the input vector raised element-wise to the power of `N - i - 1`.

HINT: Such a matrix with a geometric progression in each row is named for *Alexandre-Theophile Vandermonde*.

In [1]:
import numpy as np

In [2]:
def create_vander_matrix(input_vector, N, is_increasing = False):
    if is_increasing == False:
        vander = []
        
        for x in input_vector:
            for i in range(N):
                u = x ** (N - i - 1)
                vander = np.append(vander, u)
                
        return vander.reshape(input_vector.size, N)
    else:
        vander = []
        
        for x in input_vector:
            for i in range(N):
                u = x ** i
                vander = np.append(vander, u)
                
        return vander.reshape(input_vector.size, N)

In [3]:
input_vector = np.array([1, 2, 3, 5])
N = 3

# is_increasing = False
create_vander_matrix(input_vector, N)

array([[ 1.,  1.,  1.],
       [ 4.,  2.,  1.],
       [ 9.,  3.,  1.],
       [25.,  5.,  1.]])

In [4]:
# is_increasing = True
create_vander_matrix(input_vector, N, is_increasing = True)

array([[ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  5., 25.]])

In [5]:
input_vector = np.array([1, 2, 3])
N = 4

# is_increasing = False
create_vander_matrix(input_vector, N)

array([[ 1.,  1.,  1.,  1.],
       [ 8.,  4.,  2.,  1.],
       [27.,  9.,  3.,  1.]])

In [6]:
# is_increasing = True
create_vander_matrix(input_vector, N, is_increasing = True)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

### Moving average

Given a sequence of `n` values `x1, x2, ..., xn` and a window size `k > 0`, the `k-th` moving average of the given sequence is defined as follows:

The moving average sequence has `n - k + 1` elements as shown below.

The moving averages with `k = 4` of a ten-value sequence `(n = 10)` is shown below
```
i     1  2  3  4  5  6  7  8  9  10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
```
Thus, the moving average sequence has `n - k + 1 = 10 - 4 + 1 = 7` values.

**Question**: Write a function to find moving average in an array over a window:
Test it over `[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]` and window of `3`.

In [7]:
def create_moving_avg(array, k):
    ith = 0
    divisor = k
    
    moving_avg = []

    for n_values in range(len(seq) - k + 1):
        values = sum(seq[ith:k])/divisor
        moving_avg = np.append(moving_avg, values)

        ith += 1
        k += 1
        
    return moving_avg

In [8]:
seq = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
k = 4

create_moving_avg(seq, k)

array([25., 35., 45., 55., 65., 75., 85.])

In [9]:
seq = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3

create_moving_avg(seq, k)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])